name: Publish Python Package

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Verify installed packages
        run: pip list

      - name: Clear dist folder
        run: rm -rf dist

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__ 
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_FOR_VAYU_CLIENT_PACKAGE }}
        run: python -m twine upload dist/*
